aws-lc: upgrade to 1.0.2
aws/aws-nitro-enclaves-acm pull request #62
Opened 2022-03-16 17:40 UTC by petreeftime

Signed-off-by: Petre Eftime <epetre@amazon.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-03-16 18:07 UTC, popegeo approved these changes

2022-03-16 20:19 UTC, alcioa requested changes
The [dependency list](https://github.com/aws/aws-nitro-enclaves-acm#dependencies) should also be updated.

2022-03-17 07:56 UTC, alcioa approved these changes

2022-03-17 08:06 UTC, popegeo approved these changes

2022-03-17 09:08 UTC, merged